# prod
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-jokl-123123-prod"
  description: "kubrix-jokl-123123-prod"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://kubrix-jokl-123123-prod.demo.kubrix.cloud
      title: Prod Instance of kubrix-jokl-123123
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/kubrix-jokl-123123
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=jokl-123123-prod'
    argocd/app-namespace: adn-kubrix
    argocd/app-name: jokl-123123-prod
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/kubrix-jokl-123123-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=kubrix-jokl-123123-prod&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: prod
  owner: "kubrix"
  system: jokl-123123
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: kubrix-jokl-123123
---
#qa
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-jokl-123123-qa"
  description: "kubrix-jokl-123123-qa"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://kubrix-jokl-123123-qa.demo.kubrix.cloud
      title: QA Instance of kubrix-jokl-123123
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/kubrix-jokl-123123
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=jokl-123123-qa'
    argocd/app-namespace: adn-kubrix
    argocd/app-name: jokl-123123-qa
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/kubrix-jokl-123123-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=kubrix-jokl-123123-qa&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: qa
  owner: "kubrix"
  system: jokl-123123
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: kubrix-jokl-123123
---
# test
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-jokl-123123-test"
  description: "kubrix-jokl-123123-test"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://kubrix-jokl-123123-test.demo.kubrix.cloud
      title: Test Instance of kubrix-jokl-123123
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/kubrix-jokl-123123
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=jokl-123123-test'
    argocd/app-namespace: adn-kubrix
    argocd/app-name: jokl-123123-test
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/kubrix-jokl-123123-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=kubrix-jokl-123123-test&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: test
  owner: "kubrix"
  system: jokl-123123
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: kubrix-jokl-123123
---
# main, at the end of catalog-info.yaml so that register link is on main component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-jokl-123123"
  description: "kubrix-jokl-123123"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: https://argocd.demo.kubrix.cloud/applications/adn-kubrix/kubrix-jokl-123123?resource=
      title: ArgoCD Application Information of kubrix-jokl-123123
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/kubrix-jokl-123123
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=kubrix-jokl-123123'
    argocd/app-namespace: adn-kubrix
    argocd/app-name: kubrix-jokl-123123
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/kubrix-jokl-123123-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
spec:
  type: service
  lifecycle: experimental
  owner: "kubrix"
  system: jokl-123123
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
---
